version: "3"
services:
  app:
    container_name: express
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "/indulge:/data/db"
  adminmongo:
    container_name: adminmongo
    image: mrvautin/adminmongo
    volumes:
      - "/indulge:/data/db"
    ports:
      - "1234:1234"
    environment:
      - HOST=0.0.0.0
